# REST API for Restarsip
# API Documentation: https://restarsip.com/docs/api/
# Base URL: http://localhost:8080/api/v1


# # Auth & User

# POST http://localhost:8080/api/v1/auth/register
# content-type: application/json

# {
#   "name": "user",
#   "email": "user@gmail.com",
#   "password": "user123",
#   "confirm_password": "user123",
#   "role": "user",
#   "handphone": "081231111111",
#   "is_active": 1
# }

# POST http://localhost:8080/api/v1/auth/login
# content-type: application/json

# {
#   "email": "admin@gmail.com",
#   "password": "admin123"
# }

# GET http://localhost:8080/api/v1/user
# content-type: application/json

# GET http://localhost:8080/api/v1/user/count
# content-type: application/json

# GET http://localhost:8080/api/v1/user/2
# content-type: application/json

# PUT http://localhost:8080/api/v1/user/2
# content-type: application/json

# {
#   "name": "user2",
#   "email": "user@gmail.com",
#   "password": "user1234",
#   "confirm_password": "user1234",
#   "role": "user",
#   "handphone": "081231111111",
#   "is_active": 1
# }

## jenis laporan

# GET http://localhost:8080/api/v1/jenis-laporan
# content-type: application/json

# GET http://localhost:8080/api/v1/jenis-laporan/2
# content-type: application/json

# POST http://localhost:8080/api/v1/jenis-laporan
# content-type: application/json

# {
#   "nama_jenis_laporan": "Laporan 2"
# }

# PUT http://localhost:8080/api/v1/jenis-laporan/2
# content-type: application/json

# {
#   "nama_jenis_laporan": "Laporan 2"
# }

# DELETE http://localhost:8080/api/v1/jenis-laporan/2
# content-type: application/json

# # Disposisi kepada

# GET http://localhost:8080/api/v1/disposisi-kepada
# content-type: application/json

# GET http://localhost:8080/api/v1/disposisi-kepada/2
# content-type: application/json

# POST http://localhost:8080/api/v1/disposisi-kepada  
# content-type: application/json

# {
#   "nama_disposisi_kepada": "Disposisi 1",
#   "nama_kordinator": "Koordinator 1",
#   "nip": "1234567890"
# }

# PUT http://localhost:8080/api/v1/disposisi-kepada/2
# content-type: application/json

# {
#   "nama_disposisi_kepada": "Disposisi 2"
# }

# DELETE http://localhost:8080/api/v1/disposisi-kepada/2
# content-type: application/json

# # disposisi petunjuk

# GET http://localhost:8080/api/v1/disposisi-petunjuk
# content-type: application/json

# GET http://localhost:8080/api/v1/disposisi-petunjuk/2
# content-type: application/json

# POST http://localhost:8080/api/v1/disposisi-petunjuk
# content-type: application/json

# {
#   "nama_disposisi_petunjuk": "Disposisi 2"
# }

# PUT http://localhost:8080/api/v1/disposisi-petunjuk/2
# content-type: application/json

# { 
#   "nama_disposisi_petunjuk": "Disposisi 2"
# }

# DELETE http://localhost:8080/api/v1/disposisi-petunjuk/2
# content-type: application/


# # sifat laporan

# GET http://localhost:8080/api/v1/sifat-laporan
# content-type: application/json

# GET http://localhost:8080/api/v1/sifat-laporan/2
# content-type: application/json

# POST http://localhost:8080/api/v1/sifat-laporan
# content-type: application/json

# {
#   "nama_sifat_laporan": "Sifat 2"
# }

# PUT http://localhost:8080/api/v1/sifat-laporan/2
# content-type: application/json

# {
#   "nama_sifat_laporan": "Sifat 2"
# }

# DELETE http://localhost:8080/api/v1/sifat-laporan/2
# content-type: application/json

# # status laporan

# GET http://localhost:8080/api/v1/status-laporan
# content-type: application/json

# GET http://localhost:8080/api/v1/status-laporan/2
# content-type: application/json

# POST http://localhost:8080/api/v1/status-laporan
# content-type: application/json

# {
#   "nama_status_laporan": "Status 2"
# }

# PUT http://localhost:8080/api/v1/status-laporan/2
# content-type: application/json

# {
#   "nama_status_laporan": "Status 2"
# }

# DELETE http://localhost:8080/api/v1/status-laporan/2
# content-type: application/json

# # surat 

# GET http://localhost:8080/api/v1/surat
# content-type: application/json

# GET http://localhost:8080/api/v1/surat/notification
# content-type: application/json

# GET http://localhost:8080/api/v1/surat/count
# content-type: application/json

  # GET http://localhost:8080/api/v1/surat/countin
  # content-type: application/json

# GET http://localhost:8080/api/v1/surat/countout
# content-type: application/json

# GET http://localhost:8080/api/v1/surat/masuk
# content-type: application/json

# GET http://localhost:8080/api/v1/surat/keluar
# content-type: application/json

# GET http://localhost:8080/api/v1/surat/2
# content-type: application/json

# POST http://localhost:8080/api/v1/surat
# content-type: application/json

# {
#   "nomor_surat": "123",
#   "perihal": "Perihal",
#   "lampiran": "Lampiran",
#   "dibuat_oleh": "Dibuat Oleh",
#   "id_sifat": 3,
#   "id_jenis": 3,
#   "tanggal_diterima": "2023-10-01",
#   "id_status": 1,
#   "nomor_agenda": "123",
#   "id_user": 1,
#   "dari": "Dari",
#   "tipe_surat": "keluar"    
# }


# PUT http://localhost:8080/api/v1/surat/12
# content-type: application/json

# {
#   "is_completed": 1
# }

# DELETE http://localhost:8080/api/v1/surat/4
# content-type: application/json
